Lift
FRCTeam1073-TheForceTeam/robot2020 pull request #19
Opened 2020-01-30 01:50 UTC by ChristianW1073

it builds 
and we fixed some interfaces ( we had motors in the lift command and interface and they should not be used in there)

2020-01-30 01:52 UTC, kcjesse02 submitted a review, later dismissed

2020-01-30 01:53 UTC, classygirl44 requested changes
Needs more comments...

2020-01-30 01:56 UTC, jjesse1972 approved these changes

2020-02-01 14:26 UTC, kcjesse02 approved these changes

2020-02-01 14:34 UTC, classygirl44 approved these changes

2020-02-01 14:34 UTC, merged