Magazine
FRCTeam1073-TheForceTeam/robot2020 pull request #45
Opened 2020-02-08 19:00 UTC by kcjesse02

Pull Request Checklist:
- [ ] You are able to understand what the code is doing on a basic level with the use of comments
- [ ] Code is formatted in a way that isn't confusing
- [ ] builds cleanly
- [ ] builds *to the robot* cleanly
- [ ] Code has been tested on the robot/roadkill/other mechanical setup and completes the task it needs to complete
---------------------------------------------------------------------------------------------------
Do not merge until #44 is merged. 
---------------------------------------------------------------------------------------------------
You need to download the Time-Of-Flight libraries so you don't get error with time of flight sensors. Here is a link with directions: [https://www.playingwithfusion.com/docview.php?docid=1205&catid=9012](https://www.playingwithfusion.com/docview.php?docid=1205&catid=9012). 
---------------------------------------------------------------------------------------------------

2020-02-08 19:05 UTC, classygirl44 requested changes
Please add more comments!!

2020-02-08 19:27 UTC, 122004 requested changes
There is a misspelling within your code.

2020-02-08 19:27 UTC, 122004 commented on src/main/java/frc/robot/subsystems/instances/Magazine.java
> +    enterance = new TimeOfFlight(1);
I believe the correct spelling is "entrance"

2020-02-08 19:27 UTC, 122004 commented on src/main/java/frc/robot/subsystems/instances/Magazine.java
> +    enterance.setRangingMode(RangingMode.Short, 20);
This should be "entrance", instead of "enterance"

2020-02-08 19:27 UTC, 122004 commented on src/main/java/frc/robot/subsystems/instances/Magazine.java
> +    if(enterance.getRange() <= ballDist){
**_Entrance._**

2020-02-08 19:27 UTC, 122004 commented on src/main/java/frc/robot/subsystems/instances/Magazine.java
> +    enterance.getRange();
**eNtRaNcE!**

2020-02-08 21:23 UTC, classygirl44 submitted a review, later dismissed
Cool

2020-02-15 19:44 UTC, BenWertz reviewed
I would change the magazine motor's ID to something other than 24, because it's the same CAN ID as the hood. I'm not sure if it's an issue, but it might be. Other than that everything's good.

2020-02-19 22:45 UTC, 122004 approved these changes
Looks good!

2020-02-20 00:18 UTC, 122004 approved these changes

2020-02-20 00:20 UTC, BenWertz approved these changes

2020-02-20 00:21 UTC, merged