Shuffleboard4
FRCTeam1073-TheForceTeam/robot2020 pull request #54
Opened 2020-02-18 02:05 UTC by ChristianW1073

Pull Request Checklist:
- [ ] You are able to understand what the code is doing on a basic level with the use of comments
- [ ] Code is formatted in a way that isn't confusing
- [ ] builds cleanly
- [ ] builds *to the robot* cleanly
- [ ] Code has been tested on the robot/roadkill/other mechanical setup and completes the task it needs to complete

2020-02-18 02:08 UTC, kcjesse02 submitted a review, later dismissed

2020-02-22 19:47 UTC, 122004 requested changes

2020-02-22 19:47 UTC, 122004 commented on src/main/java/frc/robot/shuffleboard/ShuffleboardWidgets.java
> +      // Drivetrain Data INCOMPLETE
The "Drivetrain Data" needs to be complete _(or at least labeled as such)_ before this is pushed.

2020-02-25 19:24 UTC, BenWertz approved these changes
I really like the (==null) statements in ShuffleboardWidgets. That's a good idea.

2020-02-25 21:57 UTC, 122004 approved these changes

2020-02-25 21:57 UTC, merged