Flywheel/Shooter code and controls
FRCTeam1073-TheForceTeam/robot2020 pull request #63
Opened 2020-02-23 22:41 UTC by BenWertz

Code now works on the complete turret (minus the turret, that is):

The flywheel uses _both_ motors and has PID (still a WIP, it undershoots by a lot, but it at least resists the load of the power cell when shooting [for the most part {it's not perfect, but that's okay}]), and the hood is using the Hall Effect sensor but it has closed-loop position (no indexing _right_ now, but I'm pretty sure it could work if I uncommented it [didn't want to risk it]).

It also has a bunch of diagnostic displays in ShooterControls.java.

2020-02-23 22:46 UTC, jjesse1972 submitted a review, later dismissed

2020-02-25 19:05 UTC, ClaudP requested changes
Please leave in Turret Indexing when merging into main unless absolutely necessary to the flywheel's current function.

2020-02-25 19:06 UTC, ClaudP approved these changes

2020-02-25 19:09 UTC, classygirl44 reviewed
Looks good!

Joke for the day: What do unicorns call their dads?

2020-02-25 19:11 UTC, r-wallis commented on src/main/java/frc/robot/commands/ShooterControls.java
> +    shooter.setHoodAngle((shooter.getMaxHoodAngle() + shooter.getMinHoodAngle()) * 0.5
should there be a comment explaining this?

2020-02-25 19:16 UTC, r-wallis commented on src/main/java/frc/robot/subsystems/instances/Shooter.java
> +      isHoodIndexed = !isHoodIndexed;
does this toggle or set to 0/false?

2020-02-25 19:17 UTC, r-wallis approved these changes

2020-02-25 19:18 UTC, merged