Auto movement commands
FRCTeam1073-TheForceTeam/robot2020 pull request #66
Opened 2020-02-26 01:39 UTC by ChristianW1073

Pull Request Checklist:
- [ ] You are able to understand what the code is doing on a basic level with the use of comments
- [ ] Code is formatted in a way that isn't confusing
- [ ] builds cleanly
- [ ] builds *to the robot* cleanly
- [ ] Code has been tested on the robot/roadkill/other mechanical setup and completes the task it needs to complete

2020-02-26 01:49 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoDriveForward.java
>      drivetrain.setVelocity(velocity, velocity);
could replace this using Java.lang.math.min()
drivetrain.setVelociey(min(velocity,maxVelocity),min(velocity,maxVelocity))

2020-02-26 01:49 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoSetFlywheel.java
> +      shooter.setFlywheelSpeed(velocity);
could replace this using Java.lang.math.min()
shooter.setFlywheelSpeed(min(velocity,maxVelocity))

2020-02-26 01:50 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoSetHood.java
> +    shooter.setHoodVelocity(velocity);
could replace this using Java.lang.math.min()
shooter.setHoodVelocity(min(velocity,maxVelocity);

2020-02-26 01:52 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoTurn.java
> +  public static autoTurn auto45left(DrivetrainInterface drivetrain) {
what about a single autoLeft and pass the angle in ... and autoRight and pass the angle in?

2020-02-26 01:53 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoTurn.java
> +    else {
min to remove the IF

2020-02-26 01:53 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoTurnTurret.java
> +    else {
min instead of the if?

2020-02-26 02:16 UTC, jjesse1972 approved these changes

2020-02-26 02:16 UTC, jjesse1972 commented on src/main/java/frc/robot/autoCommands/autoDriveForward.java
>      drivetrain.setVelocity(velocity, velocity);
[Nit] Indent.

2020-02-26 02:16 UTC, jjesse1972 commented on src/main/java/frc/robot/autoCommands/autoSetFlywheel.java
> +    return false;
Does the command ever exit?

2020-02-26 02:16 UTC, jjesse1972 commented on src/main/java/frc/robot/autoCommands/autoSetHood.java
> +    velocity = accelConstant * (rotation - (currentHoodPosition - initHoodPosition));
Needs to be tested

2020-02-26 02:18 UTC, jjesse1972 submitted a review, later dismissed

2020-02-26 11:51 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoDriveForward.java
> +    // secures that it doesn't try to go faster than it's able to
probably meant ensures here?

2020-02-26 11:51 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoSetFlywheel.java
> +    // secures that the flywheel doesn't try to go faster than it's able to
ensures?

2020-02-26 11:52 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoTurnTurret.java
> +    // secures that it doesn't try to go faster than it's able to
ensures?

2020-02-27 00:50 UTC, r-wallis commented on src/main/java/frc/robot/autoCommands/autoTurn.java
> +    drivetrain.setVelocity( - Math.min(velocity, maxVelocity), java.lang.Math.min(velocity, maxVelocity));
extra java.lang?

2020-02-27 00:54 UTC, 122004 requested changes
Doesn't build.

2020-02-27 01:03 UTC, 122004 commented
### Here is the specific error:

> "cannot find symbol"

#### On this line:

> driveAuto = autoTurn.auto90left(drivetrain);

2020-02-27 01:05 UTC, 122004 approved these changes

2020-02-27 01:12 UTC, r-wallis approved these changes

2020-02-27 01:14 UTC, merged